package pl.szynolandia.singerstats;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.media.*;import android.net.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity{
    ProjectData project=new ProjectData();MediaPlayer player;Handler h=new Handler();LinearLayout body,timeline,singerBox;TextView time;EditText lyrics;VisualizerView viz;ProgressBar progress;VideoView video;Uri lastVideo;int selectedSinger=-1;
    int BG=Color.rgb(18,18,18),FG=Color.rgb(235,235,235),CARD=Color.rgb(38,38,38);
    public void onCreate(Bundle b){super.onCreate(b);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);TextView title=txt("Singer Stats Visualizer",22);root.addView(title);LinearLayout nav=row();Button a=btn("Projekt"),t=btn("Timing"),v=btn("Podgląd / eksport");nav.addView(a);nav.addView(t);nav.addView(v);root.addView(nav);ScrollView s=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(14,10,14,25);s.addView(body);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);a.setOnClickListener(x->projectTab());t.setOnClickListener(x->timingTab());v.setOnClickListener(x->previewTab());projectTab();h.post(tick);}
    Runnable tick=new Runnable(){public void run(){if(player!=null&&time!=null)time.setText(VisualizerView.fmt(player.getCurrentPosition()/1000.0)+" / "+VisualizerView.fmt(player.getDuration()/1000.0));if(viz!=null)viz.setTime(player==null?0:player.getCurrentPosition()/1000.0);h.postDelayed(this,50);}};
    TextView txt(String s,int z){TextView x=new TextView(this);x.setText(s);x.setTextColor(FG);x.setTextSize(z);x.setPadding(8,8,8,8);return x;}Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);return r;}void clear(){body.removeAllViews();}
    void projectTab(){clear();LinearLayout r=row();Button op=btn("Otwórz .ssp.json"),sv=btn("Zapisz .ssp.json");r.addView(op);r.addView(sv);body.addView(r);op.setOnClickListener(x->open("application/json",30));sv.setOnClickListener(x->create("application/json","SingerStats.ssp.json",31));Button audio=btn("Wybierz audio");body.addView(audio);audio.setOnClickListener(x->open("audio/*",10));time=txt("0:00.00",16);body.addView(time);LinearLayout vr=row();Button cover=btn("Okładka/tło"),border=btn("Kolor ramki tekstu");vr.addView(cover);vr.addView(border);body.addView(vr);cover.setOnClickListener(x->open("image/*",11));border.setOnClickListener(x->colors(project.lyricsBorderColor,c->project.lyricsBorderColor=c));body.addView(txt("Wokaliści",18));singerBox=new LinearLayout(this);singerBox.setOrientation(LinearLayout.VERTICAL);body.addView(singerBox);renderSingers();Button add=btn("+ Dodaj wokalistę");body.addView(add);add.setOnClickListener(x->addSinger());body.addView(txt("Tekst",18));lyrics=new EditText(this);lyrics.setTextColor(FG);lyrics.setMinLines(7);StringBuilder sb=new StringBuilder();for(LyricLine l:project.lyrics)sb.append(l.text).append("\n");lyrics.setText(sb.toString());body.addView(lyrics);Button gen=btn("Generuj oś czasu");body.addView(gen);gen.setOnClickListener(x->{project.lyrics.clear();int id=project.singers.get(0).id;for(String q:lyrics.getText().toString().split("\\n"))if(!q.trim().isEmpty()){LyricLine l=new LyricLine();l.text=q.trim();l.singerIds.add(id);project.lyrics.add(l);}timingTab();});}
    void renderSingers(){if(singerBox==null)return;singerBox.removeAllViews();for(Singer s:project.singers){LinearLayout r=row();TextView n=txt(s.name+(s.imagePath!=null?"  [foto]":""),16);try{n.setTextColor(Color.parseColor(s.color));}catch(Exception e){}Button c=btn("Kolor"),im=btn("Zdjęcie");r.addView(n,new LinearLayout.LayoutParams(0,-2,1));r.addView(c);r.addView(im);singerBox.addView(r);c.setOnClickListener(x->colors(s.color,z->{s.color=z;renderSingers();}));im.setOnClickListener(x->{selectedSinger=s.id;open("image/*",12);});}}
    void addSinger(){EditText e=new EditText(this);new AlertDialog.Builder(this).setTitle("Nowy wokalista").setView(e).setPositiveButton("Dodaj",(d,w)->{String n=e.getText().toString().trim();if(!n.isEmpty()){project.singers.add(new Singer(project.nextSingerId++,n,"#8a5cff"));renderSingers();}}).setNegativeButton("Anuluj",null).show();}
    void timingTab(){clear();time=txt("0:00.00",18);body.addView(time);LinearLayout r=row();Button b=btn("-5s"),p=btn("Play / Pauza"),f=btn("+5s");r.addView(b);r.addView(p);r.addView(f);body.addView(r);b.setOnClickListener(x->seek(-5000));p.setOnClickListener(x->play());f.setOnClickListener(x->seek(5000));timeline=new LinearLayout(this);timeline.setOrientation(LinearLayout.VERTICAL);body.addView(timeline);for(int i=0;i<project.lyrics.size();i++)lineCard(i);}
    void lineCard(int i){LyricLine l=project.lyrics.get(i);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(8,8,8,8);box.setBackgroundColor(CARD);box.addView(txt((i+1)+". "+l.text,15));Button who=btn(names(l));box.addView(who);who.setOnClickListener(x->pick(i));LinearLayout r=row();EditText st=num(l.start),en=num(l.end);Button bs=btn("START"),be=btn("KONIEC");r.addView(st,new LinearLayout.LayoutParams(0,-2,1));r.addView(bs);r.addView(en,new LinearLayout.LayoutParams(0,-2,1));r.addView(be);box.addView(r);bs.setOnClickListener(x->{l.start=now();st.setText(f(l.start));});be.setOnClickListener(x->{l.end=now();en.setText(f(l.end));});st.setOnFocusChangeListener((x,z)->{if(!z)l.start=parse(st);});en.setOnFocusChangeListener((x,z)->{if(!z)l.end=parse(en);});timeline.addView(box);}
    EditText num(Double d){EditText e=new EditText(this);e.setTextColor(FG);e.setInputType(2|8192);if(d!=null)e.setText(f(d));return e;}Double parse(EditText e){try{return Double.parseDouble(e.getText().toString().replace(',','.'));}catch(Exception x){return null;}}String f(Double d){return d==null?"":String.format(Locale.US,"%.2f",d);}double now(){return player==null?0:player.getCurrentPosition()/1000.0;}
    void pick(int idx){LyricLine l=project.lyrics.get(idx);String[]ns=new String[project.singers.size()];boolean[]ck=new boolean[ns.length];for(int i=0;i<ns.length;i++){ns[i]=project.singers.get(i).name;ck[i]=l.singerIds.contains(project.singers.get(i).id);}new AlertDialog.Builder(this).setTitle("Kto śpiewa?").setMultiChoiceItems(ns,ck,(d,which,isChecked)->ck[which]=isChecked).setPositiveButton("OK",(d,w)->{l.singerIds.clear();for(int i=0;i<ck.length;i++)if(ck[i])l.singerIds.add(project.singers.get(i).id);if(l.singerIds.isEmpty())l.singerIds.add(project.singers.get(0).id);timingTab();}).show();}
    String names(LyricLine l){StringBuilder b=new StringBuilder();for(Singer s:project.singers)if(l.singerIds.contains(s.id)){if(b.length()>0)b.append(" + ");b.append(s.name);}return b.toString();}
    void previewTab(){clear();viz=new VisualizerView(this);viz.setProject(project);int w=getResources().getDisplayMetrics().widthPixels-28;body.addView(viz,new LinearLayout.LayoutParams(-1,(int)(w*16f/9)));progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);body.addView(progress);LinearLayout r=row();Button full=btn("Eksport całości"),part=btn("Fragment OD-DO");r.addView(full);r.addView(part);body.addView(r);full.setOnClickListener(x->{if(player!=null)export(0,player.getDuration()/1000.0);});part.setOnClickListener(x->fragment());video=new VideoView(this);body.addView(video,new LinearLayout.LayoutParams(-1,(int)(w*16f/9)));Button watch=btn("Odtwórz wygenerowany MP4");body.addView(watch);watch.setOnClickListener(x->{if(lastVideo!=null){video.setVideoURI(lastVideo);video.setMediaController(new MediaController(this));video.start();}});}
    void fragment(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);EditText a=num(0d),z=num(player==null?0d:player.getDuration()/1000.0);b.addView(a);b.addView(z);new AlertDialog.Builder(this).setTitle("Fragment OD-DO (sekundy)").setView(b).setPositiveButton("Generuj",(d,w)->{Double x=parse(a),y=parse(z);if(x!=null&&y!=null&&y>x)export(x,y);}).show();}
    void export(double a,double z){VideoExporter.export(this,project,a,z,30,new VideoExporter.Listener(){public void progress(int p){runOnUiThread(()->progress.setProgress(p));}public void done(Uri u){runOnUiThread(()->{lastVideo=u;Toast.makeText(MainActivity.this,"MP4 zapisany w galerii",Toast.LENGTH_LONG).show();});}public void error(String e){runOnUiThread(()->new AlertDialog.Builder(MainActivity.this).setTitle("Błąd eksportu").setMessage(e).setPositiveButton("OK",null).show());}});}
    void play(){if(player!=null){if(player.isPlaying())player.pause();else player.start();}}void seek(int x){if(player!=null)player.seekTo(Math.max(0,Math.min(player.getDuration(),player.getCurrentPosition()+x)));}
    interface CR{void done(String c);}void colors(String cur,CR cb){String[]c={"#ff0050","#00f2ea","#ffe600","#8a5cff","#ff7b00","#2ecc71","#ffffff","#ff4fd8","#00a8ff"};new AlertDialog.Builder(this).setTitle("Kolor").setItems(c,(d,i)->cb.done(c[i])).show();}
    void open(String mime,int code){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType(mime);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,code);}void create(String mime,String name,int code){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType(mime);i.putExtra(Intent.EXTRA_TITLE,name);startActivityForResult(i,code);}
    protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(res!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();try{if(req==10){String p=copy(u,"audio"+ext(u));if(player!=null)player.release();player=new MediaPlayer();player.setDataSource(p);player.prepare();project.audioPath=p;}else if(req==11)project.coverPath=copy(u,"cover"+ext(u));else if(req==12){for(Singer s:project.singers)if(s.id==selectedSinger)s.imagePath=copy(u,"singer_"+s.id+ext(u));}else if(req==30){project=ProjectData.from(new JSONObject(read(u)));project.audioPath=null;project.coverPath=null;for(Singer s:project.singers)s.imagePath=null;projectTab();}else if(req==31)write(u,project.json().toString(2));}catch(Exception e){new AlertDialog.Builder(this).setMessage(e.toString()).setPositiveButton("OK",null).show();}}
    String copy(Uri u,String n)throws Exception{File d=new File(getFilesDir(),"media");d.mkdirs();File f=new File(d,n);try(InputStream in=getContentResolver().openInputStream(u);OutputStream out=new FileOutputStream(f)){byte[]b=new byte[65536];int k;while((k=in.read(b))>0)out.write(b,0,k);}return f.getAbsolutePath();}String ext(Uri u){String t=getContentResolver().getType(u);if(t==null)return".bin";if(t.contains("mpeg"))return".mp3";if(t.contains("png"))return".png";if(t.contains("webp"))return".webp";if(t.contains("jpeg"))return".jpg";return".bin";}String read(Uri u)throws Exception{try(InputStream in=getContentResolver().openInputStream(u)){ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]b=new byte[65536];int n;while((n=in.read(b))>0)o.write(b,0,n);return o.toString("UTF-8");}}void write(Uri u,String s)throws Exception{try(OutputStream o=getContentResolver().openOutputStream(u)){o.write(s.getBytes("UTF-8"));}}
}
