package pl.szynolandia.singerstats;

import android.content.*;import android.graphics.*;import android.net.*;import android.os.*;import android.provider.MediaStore;import com.arthenica.ffmpegkit.*;import java.io.*;import java.nio.*;import java.util.*;

public class VideoExporter {
    interface Listener{void progress(int p);void done(Uri u);void error(String e);}
    static void export(Context ctx,ProjectData pr,double from,double to,int fps,Listener li){new Thread(()->{String pipe=null;try{if(pr.audioPath==null||!new File(pr.audioPath).exists())throw new Exception("Brak pliku audio.");File out=new File(ctx.getCacheDir(),"SingerStats_"+System.currentTimeMillis()+".mp4");pipe=FFmpegKitConfig.registerNewFFmpegPipe(ctx);double dur=to-from;int frames=Math.max(1,(int)Math.ceil(dur*fps));String cmd="-y -f rawvideo -pixel_format bgra -video_size 1080x1920 -framerate "+fps+" -i \""+pipe+"\" -ss "+String.format(Locale.US,"%.3f",from)+" -t "+String.format(Locale.US,"%.3f",dur)+" -i \""+pr.audioPath+"\" -map 0:v:0 -map 1:a:0 -c:v h264_mediacodec -b:v 8000000 -pix_fmt yuv420p -c:a aac -b:a 192k -shortest \""+out.getAbsolutePath()+"\"";final String pp=pipe;FFmpegKit.executeAsync(cmd,session->{try{if(ReturnCode.isSuccess(session.getReturnCode()))li.done(save(ctx,out));else li.error(session.getAllLogsAsString());}catch(Exception e){li.error(e.toString());}try{FFmpegKitConfig.closeFFmpegPipe(pp);}catch(Exception ignored){}});try(FileOutputStream fos=new FileOutputStream(pipe)){ByteBuffer buf=ByteBuffer.allocate(1080*1920*4);for(int i=0;i<frames;i++){Bitmap b=VisualizerView.render(pr,from+i/(double)fps);buf.clear();b.copyPixelsToBuffer(buf);fos.write(buf.array(),0,buf.position());b.recycle();li.progress((i+1)*100/frames);}}}catch(Exception e){li.error(e.toString());if(pipe!=null)try{FFmpegKitConfig.closeFFmpegPipe(pipe);}catch(Exception ignored){}}}).start();}
    static Uri save(Context c,File src)throws Exception{ContentValues v=new ContentValues();v.put(MediaStore.Video.Media.DISPLAY_NAME,src.getName());v.put(MediaStore.Video.Media.MIME_TYPE,"video/mp4");if(Build.VERSION.SDK_INT>=29)v.put(MediaStore.Video.Media.RELATIVE_PATH,"Movies/Singer Stats Visualizer");Uri u=c.getContentResolver().insert(MediaStore.Video.Media.EXTERNAL_CONTENT_URI,v);if(u==null)throw new Exception("Nie udało się zapisać filmu.");try(InputStream in=new FileInputStream(src);OutputStream out=c.getContentResolver().openOutputStream(u)){byte[]b=new byte[1024*1024];int n;while((n=in.read(b))>0)out.write(b,0,n);}return u;}
}
