package pl.szynolandia.singerstats;

import android.content.*;import android.graphics.*;import android.view.*;import java.util.*;

public class VisualizerView extends View {
    ProjectData project; double time;
    public VisualizerView(Context c){super(c);setBackgroundColor(Color.BLACK);} public void setProject(ProjectData p){project=p;invalidate();} public void setTime(double t){time=t;invalidate();}
    protected void onDraw(Canvas c){super.onDraw(c);if(project==null)return;float s=Math.min(getWidth()/1080f,getHeight()/1920f);c.save();c.translate((getWidth()-1080*s)/2,(getHeight()-1920*s)/2);c.scale(s,s);drawScene(c,project,time);c.restore();}
    static Bitmap crop(String path,int w,int h){if(path==null)return null;Bitmap src=BitmapFactory.decodeFile(path);if(src==null)return null;float z=Math.max(w/(float)src.getWidth(),h/(float)src.getHeight());Bitmap scaled=Bitmap.createScaledBitmap(src,Math.round(src.getWidth()*z),Math.round(src.getHeight()*z),true);int x=Math.max(0,(scaled.getWidth()-w)/2),y=Math.max(0,(scaled.getHeight()-h)/2);return Bitmap.createBitmap(scaled,x,y,Math.min(w,scaled.getWidth()-x),Math.min(h,scaled.getHeight()-y));}
    public static Bitmap render(ProjectData p,double t){Bitmap b=Bitmap.createBitmap(1080,1920,Bitmap.Config.ARGB_8888);drawScene(new Canvas(b),p,t);return b;}
    static void drawScene(Canvas c,ProjectData pr,double t){Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);c.drawColor(Color.rgb(5,5,5));Bitmap cover=crop(pr.coverPath,1080,1920);if(cover!=null){c.drawBitmap(cover,0,0,p);p.setColor(Color.argb(120,0,0,0));c.drawRect(0,0,1080,1920,p);}p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.WHITE);p.setTextSize(54);p.setFakeBoldText(true);c.drawText("KTO ILE ŚPIEWA?",540,105,p);p.setTextSize(38);p.setFakeBoldText(false);c.drawText(fmt(t),540,165,p);
        LyricLine active=null;for(LyricLine l:pr.lyrics)if(l.start!=null&&l.end!=null&&t>=l.start&&t<=l.end){active=l;break;}if(active!=null){p.setStyle(Paint.Style.FILL);p.setColor(Color.argb(155,0,0,0));c.drawRoundRect(75,650,1005,1015,30,30,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(7);try{p.setColor(Color.parseColor(pr.lyricsBorderColor));}catch(Exception e){p.setColor(0xffff0050);}c.drawRoundRect(75,650,1005,1015,30,30,p);p.setStyle(Paint.Style.FILL);ArrayList<Singer>a=new ArrayList<>();for(Singer s:pr.singers)if(active.singerIds.contains(s.id))a.add(s);int x=120;for(Singer s:a){Bitmap av=crop(s.imagePath,88,88);RectF r=new RectF(x,690,x+88,778);if(av!=null)c.drawBitmap(av,null,r,p);else{try{p.setColor(Color.parseColor(s.color));}catch(Exception e){p.setColor(Color.GRAY);}c.drawOval(r,p);}x+=102;if(x>750)break;}StringBuilder names=new StringBuilder();for(Singer s:a){if(names.length()>0)names.append(" + ");names.append(s.name.toUpperCase());}p.setTextAlign(Paint.Align.LEFT);p.setTextSize(34);p.setFakeBoldText(true);try{p.setColor(a.isEmpty()?Color.WHITE:Color.parseColor(a.get(0).color));}catch(Exception e){p.setColor(Color.WHITE);}c.drawText(names.toString(),120,840,p);p.setFakeBoldText(false);p.setColor(Color.WHITE);p.setTextSize(44);wrap(c,p,active.text,120,920,830,52,2);}
        p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.WHITE);p.setTextSize(34);p.setFakeBoldText(true);c.drawText("CZAS UTWORU  "+fmt(t),540,1160,p);c.drawText("STATYSTYKI CZASU",540,1260,p);p.setFakeBoldText(false);ArrayList<Object[]> rows=stats(pr,t);double total=0;for(Object[]r:rows)total+=(double)r[1];for(int i=0;i<Math.min(5,rows.size());i++){Singer s=(Singer)rows.get(i)[0];double sec=(double)rows.get(i)[1],pct=total>0?sec/total:0;float y=1350+i*100;p.setTextAlign(Paint.Align.LEFT);p.setTextSize(28);p.setColor(Color.WHITE);c.drawText(s.name,100,y,p);p.setTextAlign(Paint.Align.RIGHT);c.drawText(String.format(Locale.US,"%.1fs • %.1f%%",sec,pct*100),970,y,p);p.setColor(Color.DKGRAY);c.drawRoundRect(100,y+20,790,y+52,16,16,p);try{p.setColor(Color.parseColor(s.color));}catch(Exception e){p.setColor(Color.WHITE);}c.drawRoundRect(100,y+20,(float)(100+690*pct),y+52,16,16,p);}}
    static ArrayList<Object[]>stats(ProjectData p,double t){ArrayList<Object[]>r=new ArrayList<>();for(Singer s:p.singers){double sec=0;for(LyricLine l:p.lyrics){if(!l.singerIds.contains(s.id)||l.start==null||l.end==null)continue;if(t>l.end)sec+=Math.max(0,l.end-l.start);else if(t>l.start)sec+=Math.max(0,t-l.start);}r.add(new Object[]{s,sec});}r.sort((a,b)->Double.compare((double)b[1],(double)a[1]));return r;}
    static String fmt(double sec){int m=(int)(sec/60);return String.format(Locale.US,"%d:%05.2f",m,sec-m*60);}static void wrap(Canvas c,Paint p,String text,float x,float y,float max,float lineH,int maxLines){String line="";int n=0;for(String w:text.split("\\s+")){String test=line.isEmpty()?w:line+" "+w;if(p.measureText(test)>max&&!line.isEmpty()){c.drawText(line,x,y+n*lineH,p);if(++n>=maxLines)return;line=w;}else line=test;}if(n<maxLines)c.drawText(line,x,y+n*lineH,p);}
}
